# Data path. adjust them!
common:
    image_file: "/home/astar/dart_ws/calib/shenzhen0207/img/000001.jpg" #"/home/astar/dart_ws/single_scene_calibration/0.png"
    pcd_file: "/home/astar/dart_ws/calib/shenzhen0207/output_ascii_cropped.pcd"
    result_file: "/home/astar/dart_ws/calib/shenzhen0207.txt"

# Camera Parameters. Adjust them!
camera:
    # camera_matrix: [10013.414549, 0.0,      1374.860012,
    #             0.0,     9973.556438,  1083.353097,
    #             0.000000, 0.000000, 1.000000]

    # dist_coeffs: [0.115390, 3.556332, 0.003539, 0.008989, 0.000000]
    
    ex_matrix: [0.00369442,-0.999963,0.00775564,0.101602,
        0.00769984,-0.00772702,-0.999941,0.0190235,
        0.999964,0.00375392,0.00767101,-0.0670998,
        0,0,0,1
    ]
    camera_matrix: [10240.519092, 0.000000, 1235.589025,
        0.000000, 10201.088569, 938.383012,
        0.000000, 0.000000, 1.000000]
    
    dist_coeffs: [0.856451, -94.718525, 0.002609, 0.004210, 0.000000]

# translation matrix from camera to rotor
cam_rotor: [ # forward, left and up are pos
    1,0,0,0,
    0,1,0,-0.54464,
    0,0,1,0.70456,
    0,0,0,1
]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/astar/dart_ws/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad

# colors:
#     lower_color: [250, 80, 250]
#     upper_color: [256, 150, 255]

