%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

# Lidar Data type(custom msg or pointcloud2)
Data.custom_msg: 0
# Initial extrinsic (usually provided by hand measurement or cad design)

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,   0.0,    0.0,
         0.0,  0.0,  -1.0,    0.0,
         1.0,   0.0,    0.0,    0.0,
         0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction
# blue lines corresponds to edges extracted from images
Canny.gray_threshold: 10
Canny.len_threshold: 30

# # Params for Voxel Cutting & Plane Fitting & Edge Extraction
# Voxel.size: 1.0
# Voxel.down_sample_size: 0.02
# Plane.min_points_size: 60
# Plane.normal_theta_min: 30
# Plane.normal_theta_max: 150
# Plane.max_size: 5
# Ransac.dis_threshold: 0.015
# Ransac.iter_num: 200
# Edge.min_dis_threshold: 0.03
# Edge.max_dis_threshold: 0.06

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
# red lines represents edges extracted from point clouds
Voxel.size: 0.7

Voxel.down_sample_size: 0.01
Plane.min_points_size: 1 # Too large: no lines
Plane.normal_theta_min: 1
Plane.normal_theta_max: 150
Plane.max_size: 100 # increase max size to include more lines. This is very important because we want to have more lines in point cloud to align with lines in images!!!!!
Ransac.dis_threshold: 0.01
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.04
Edge.max_dis_threshold: 0.01

# Params for color point clouds
Color.dense: 1
Color.intensity_threshold: 10